"""Write index.html from audio-src/timing.json (scene starts sit on the 110 BPM grid)."""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
T = json.load(open(os.path.join(ROOT, "audio-src/timing.json")))
total = T["total"]

hosts = "\n".join(
    f'      <div id="{s["id"]}" class="clip" data-composition-id="{s["id"]}" '
    f'data-composition-src="compositions/{s["id"]}.html" data-start="{s["start"]}" '
    f'data-duration="{s["dur"]}" data-track-index="1" data-width="1080" data-height="1920"></div>'
    for s in T["scenes"]
    if os.path.exists(os.path.join(ROOT, f"compositions/{s['id']}.html")))
audio = "\n".join(
    f'      <audio id="a-{n}" src="assets/audio/{n}.wav" data-start="0" data-duration="{total}" '
    f'data-track-index="{i}" data-volume="1"></audio>'
    for i, n in ((10, "vo"), (12, "sfx")))

html = f"""<!doctype html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1080, height=1920" />
    <title>Deviens un humain 10/10</title>
    <!-- Generated by tools/assemble.py from audio-src/timing.json -->
    <script src="assets/vendor/gsap.min.js"></script>
    <script src="assets/timing.js"></script>
    <script src="assets/hf10.js"></script>
    <style>
      * {{ margin: 0; padding: 0; box-sizing: border-box; }}
      html, body {{ width: 1080px; height: 1920px; overflow: hidden; background: #0a0a0a; }}
      #root {{ position: relative; width: 100%; height: 100%; overflow: hidden; background: #0a0a0a; }}
      .clip {{ position: absolute; inset: 0; }}
    </style>
  </head>
  <body>
    <div id="root" data-composition-id="main" data-start="0" data-duration="{total}" data-width="1080" data-height="1920">
{hosts}
{audio}
    </div>
    <script>
      const tl = gsap.timeline({{ paused: true }});
      window.__timelines["main"] = tl;
    </script>
  </body>
</html>
"""
open(os.path.join(ROOT, "index.html"), "w").write(html)
print("index.html:", len(T["scenes"]), "scenes,", total, "s")
