"""Scene/VO layout on the 110 BPM grid. Single source of truth for timing.

Writes assets/timing.js (read by every scene) and audio-src/timing.json
(read by tools/build_audio.py)."""
import json, math, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BPM = 110
BEAT = 60 / BPM
SIX = BEAT / 4  # 16th note

segs = json.load(open(os.path.join(ROOT, "audio-src/vo/segments.json")))

# scene id -> VO lines it carries
SCENES = [
    ("s01-hook", ["1"]),
    ("s02-salle", ["2"]),
    ("s03-eau-sommeil", ["3", "4"]),
    ("s04-lecture", ["5"]),
    ("s05-meditation-entourage", ["6", "7"]),
    ("s06-recap", []),
    ("s07-cta", ["8"]),
]
LEAD = {"s01-hook": 2 * SIX}
SENT_GAP = 0.12
LINE_GAP = 0.40
TAIL = 0.30
FIXED_BEATS = {"s06-recap": 10}
END_TAIL = {"s07-cta": 1.3}


def up(t, q):
    return math.ceil(round(t / q, 6)) * q


scenes, vo = [], []
t = 0.0
for sid, lines in SCENES:
    start = t
    cur = start + LEAD.get(sid, 2 * SIX)
    sents = []
    for li, line in enumerate(lines):
        if li:
            cur += LINE_GAP
        for si, s in enumerate(segs[line]):
            if si:
                cur = up(cur + SENT_GAP, SIX)
            sents.append({"line": int(line), "idx": si, "text": s["text"],
                          "start": round(cur - start, 4), "dur": s["dur"]})
            vo.append({"file": s["file"], "at": round(cur, 4)})
            cur += s["dur"]
    if sid in FIXED_BEATS:
        beats = FIXED_BEATS[sid]
    else:
        beats = math.ceil(round((cur + END_TAIL.get(sid, TAIL) - start) / BEAT, 6))
    dur = beats * BEAT
    scenes.append({"id": sid, "start": round(start, 4), "dur": round(dur, 4),
                   "beats": beats, "sentences": sents})
    t = start + dur

total = round(t, 4)
data = {"bpm": BPM, "beat": BEAT, "total": total, "scenes": scenes, "vo": vo}
json.dump(data, open(os.path.join(ROOT, "audio-src/timing.json"), "w"),
          ensure_ascii=False, indent=1)
with open(os.path.join(ROOT, "assets/timing.js"), "w") as f:
    f.write("// Generated by tools/layout.py — do not edit by hand.\n")
    f.write("window.HF_TIMING = " + json.dumps(
        {"bpm": BPM, "beat": BEAT, "total": total,
         "scenes": {s["id"]: {"start": s["start"], "dur": s["dur"],
                              "vo": [[x["start"], x["dur"]] for x in s["sentences"]]}
                    for s in scenes}}, ensure_ascii=False) + ";\n")

for s in scenes:
    print(f'{s["id"]:26s} start {s["start"]:6.2f} dur {s["dur"]:5.2f} ({s["beats"]} beats)')
    for x in s["sentences"]:
        print(f'    {x["start"]:5.2f} +{x["dur"]:.2f}  {x["text"]}')
print("TOTAL", total)
